#!/usr/bin/env python

import argparse
import os
from shutil import copy2, copytree

parser = argparse.ArgumentParser()
parser.add_argument("files", nargs="*", help="The files to export.")
args = parser.parse_args()

ecp_path = "/tmp/ecp"

if args.files:
    with open(ecp_path, "a+") as f:
        for efile in args.files:
            file_path = os.path.abspath(efile)
            f.write("{}\n".format(file_path))
            print("Exported {}".format(file_path))
else:
    with open(ecp_path, "r+") as f:
        for line in f:
            line = line[:-1]  # Remove \n
            if os.path.isdir(line):
                dest = "{}/{}".format(os.getcwd(), os.path.basename(line))
                copytree(line, dest)
            else:
                dest = os.getcwd()
                copy2(line, dest)
            print("Copied {} to {}".format(line, dest))

        # Empty file
        f.seek(0)
        f.write("")
        f.truncate()
